CREATE TABLE Company
(
	Id SERIAL PRIMARY KEY,
    CompanyName CHARACTER VARYING(30) NOT NULL
);
CREATE TABLE Package
(
	Id SERIAL PRIMARY KEY,
    PackageName CHARACTER VARYING(30) NOT NULL,
	CompanyId INTEGER NOT NULL,
	FOREIGN KEY (CompanyId) REFERENCES Company (Id)
);
CREATE TABLE Developer
(
	Id SERIAL PRIMARY KEY,
    DeveloperName CHARACTER VARYING(50) NOT NULL,
	CompanyId INTEGER NOT NULL,
	FOREIGN KEY (CompanyId) REFERENCES Company (Id)
);
CREATE TABLE Users
(
	Id SERIAL PRIMARY KEY,
    UserName CHARACTER VARYING(50) NOT NULL
);
CREATE TABLE Game
(
	Id SERIAL PRIMARY KEY,
	GameName CHARACTER VARYING(30) NOT NULL,
	Prices DECIMAL NOT NULL,
	Genre CHARACTER VARYING(30) NOT NULL,
	Languages CHARACTER VARYING(30) NOT NULL,
	Country CHARACTER VARYING(30) NOT NULL,
	UsersId INTEGER NOT NULL,
	CompanyId INTEGER NOT NULL,
	FOREIGN KEY (UsersId) REFERENCES Users (Id),
	FOREIGN KEY (CompanyId) REFERENCES Company (Id)	
);
CREATE TABLE Status
(
	Id SERIAL PRIMARY KEY,
	Description CHARACTER VARYING(50) NOT NULL,
	GameId INTEGER NOT NULL,
	FOREIGN KEY (GameId) REFERENCES Game(Id)
);
CREATE TABLE Cart
(
	Id SERIAL PRIMARY KEY,
	CountOrder INTEGER NOT NULL
);
CREATE TABLE Orders
(
	Id SERIAL PRIMARY KEY,
	Prices DECIMAL NOT NULL,
	StateOrder CHARACTER VARYING(30) NOT NULL,
	GameId INTEGER NOT NULL,
	CartId INTEGER NOT NULL,
	FOREIGN KEY (GameId) REFERENCES Game (Id),
	FOREIGN KEY (CartId) REFERENCES Cart (Id)
);
CREATE TABLE Transactions
(
	Id SERIAL PRIMARY KEY,
	Status CHARACTER VARYING(50) NOT NULL,
	UsersId INTEGER NOT NULL,
	OrdersId INTEGER NOT NULL,
	FOREIGN KEY (UsersId) REFERENCES Users (Id),
	FOREIGN KEY (OrdersId) REFERENCES Orders (Id)
);
